<?xml version="1.0"?>

<!-- Copyright 2013 Arn-O. See the LICENSE file at the top-level directory of this distribution and at https://github.com/Arn-O/youbot_ros_tools/blob/master/LICENSE. -->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="youbot">

  <xacro:property name="M_PI" value="3.1415926535897931"/>
  <!-- used for having a more realistic behavior -->   
  <xacro:property name="effort_correct" value="5.0" />

  <!-- Import the spec provided by youBot store -->
  <xacro:include filename="$(find youbot_description)/urdf/spec.urdf.xacro"/>

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find youbot_description)/urdf/youbot.gazebo"/>

  <xacro:macro name="base">
    <!-- #### base #### -->
    <!-- footprint link -->
    <link name="base_footprint">
      <inertial>
        <mass value="0.001"/>
	<inertia ixx="0.000001" iyy="0.000001" izz="0.000001"
                 ixy="0.000000" ixz="0.000001" iyz="0.000001" />
      </inertial>
      <visual>
        <geometry>
          <box size="0.001 0.001 0.001"/>
        </geometry>
      </visual>
    </link>
    <!-- base link -->
    <link name="base_link">
      <inertial>
	<mass value="${base_mass}"/>
	<!-- cuboid used as an approximation -->
	<inertia ixx="0.273333" iyy="0.593333" izz="0.801333"
	         ixy="0.000" ixz="0.000" iyz="0.000"/>
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://youbot_description/meshes/base_frame.dae"/>
        </geometry>
      </visual>
    </link>
    <!-- base joint -->
    <joint name="base_joint" type="fixed">
      <origin xyz="${base_pose_x} ${base_pose_y} ${base_pose_z}"/>
      <parent link="base_footprint"/>
      <child link="base_link"/>
    </joint>

    <!-- #### plate #### -->
    <!-- plate links -->
    <link name="plate_link">
      <inertial>
        <mass value="${plate_mass}"/>
	<inertia ixx="0.002000" iyy="0.002000" izz="0.002000"
	         ixy="0.000000" ixz="0.000000" iyz="0.000000"/>
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://youbot_description/meshes/plate.dae"/>
        </geometry>
      </visual>
    </link>
    <!-- plate joint -->
    <joint name="plate_joint" type="fixed">
      <origin xyz="${plate_pose_x} ${plate_pose_y} ${plate_pose_z}"/>
      <parent link="base_link"/>
      <child link="plate_link"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="wheels" params="position x y">
    <!-- ### wheels ### -->
    <link name="wheel_${position}_link">
      <inertial>
        <mass value="${wheel_mass}"/>
	<inertia ixx="0.001400" iyy="0.001400" izz="0.001400"
	         ixy="0.000000" ixz="0.000000" iyz="0.000000"/>
      </inertial>
      <visual>
        <geometry>
          <sphere radius="${wheel_radius}"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <sphere radius="${wheel_radius}"/>
        </geometry>
      </collision>
    </link>
    <joint name="wheel_${position}_joint" type="fixed">
      <origin xyz="${wheel_pose_x * x} ${wheel_pose_y * y} ${wheel_pose_z}"/>
      <parent link="base_link"/>
      <child link="wheel_${position}_link"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="arm_base">
    <!-- #### arm_base #### -->
    <link name="arm_base_link">
      <inertial>
        <mass value="${arm_base_mass}"/>
        <inertia ixx="0.010" ixy="0.000" ixz="0.000" iyy="0.010" iyz="0.000" izz="0.010"/>
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://youbot_description/meshes/arm_base_frame.dae"/>
        </geometry>
      </visual>
    </link>
    <joint name="arm_base_joint" type="fixed">
      <origin xyz="${arm_base_pose_x} ${arm_base_pose_y} ${arm_base_pose_z}"
              rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="arm_base_link"/>
    </joint>
  </xacro:macro>

  <!-- #### arm #### -->
  <xacro:macro name="arm">
    <!-- ### arm_1 ### -->
    <!-- arm_1 link -->
    <link name="arm_1_link">
      <inertial>
        <xacro:arm_1_inertial/>
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://youbot_description/meshes/arm_joint_1.dae"/>
        </geometry>
      </visual>
    </link>
    <!-- arm_1 joint -->
    <joint name="arm_1_joint" type="revolute">
      <xacro:arm_1_joint/>
      <child link="arm_1_link"/>
    </joint>
    <transmission name="tran1">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="arm_1_joint"/>
      <actuator name="motor1">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <!-- ### arm_2 ### -->
    <!-- arm_2 link -->
    <link name="arm_2_link">
      <inertial>
        <xacro:arm_2_inertial/>
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://youbot_description/meshes/arm_joint_2.dae"/>
        </geometry>
      </visual>
    </link>
    <!-- arm_2 joint -->
    <joint name="arm_2_joint" type="revolute">
      <xacro:arm_2_joint/>
      <child link="arm_2_link"/>
    </joint>
    <transmission name="tran2">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="arm_2_joint"/>
      <actuator name="motor2">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <!-- ### arm_3 ### -->
    <!-- arm_3 link -->
    <link name="arm_3_link">
      <inertial>
        <xacro:arm_3_inertial/>
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://youbot_description/meshes/arm_joint_3.dae"/>
        </geometry>
      </visual>
    </link>
    <!-- arm_3 joint -->
    <joint name="arm_3_joint" type="revolute">
      <xacro:arm_3_joint/>
      <child link="arm_3_link"/>
    </joint>
    <transmission name="tran3">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="arm_3_joint"/>
      <actuator name="motor3">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <!-- ### arm_4 ### -->
    <!-- arm_4 link -->
    <!-- <link name="arm_4_link">
      <inertial>
        <xacro:arm_4_inertial/>
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://youbot_description/meshes/arm_joint_4.dae"/>
        </geometry>
      </visual>
    </link> -->
    <!-- arm_4 joint -->
    <!-- <joint name="arm_4_joint" type="revolute">
      <xacro:arm_4_joint/>
      <child link="arm_4_link"/>
    </joint>
    <transmission name="tran4">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="arm_4_joint"/>
      <actuator name="motor4">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission> -->

    <!-- ### arm_5 ### -->
    <!-- arm_5 link -->
    <!-- <link name="arm_5_link">
      <inertial>
        <xacro:arm_5_inertial/>
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://youbot_description/meshes/arm_joint_5.dae"/>
        </geometry>
      </visual>
    </link> -->
    <!-- arm_5 joint -->
    <!-- <joint name="arm_5_joint" type="revolute">
      <xacro:arm_5_joint/>
      <child link="arm_5_link"/>
    </joint>
    <transmission name="tran5">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="arm_5_joint"/>
      <actuator name="motor5">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission> -->
  </xacro:macro>

  <xacro:macro name="gripper">
    <!-- ### gripper_base ### -->
    <!-- gripper_base link -->
    <link name="gripper_base_link">
      <inertial>
        <mass value="${gripper_base_link_mass}"/>
        <xacro:gripper_base_inertia/>
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://youbot_description/meshes/gripper_base_frame.dae"/>
        </geometry>
      </visual>
    </link>
    <!-- gripper_base joint -->
    <joint name="gripper_base_joint" type="fixed">
      <origin xyz="${gripper_base_link_pose_x} ${gripper_base_link_pose_y} ${gripper_base_link_pose_z}"   
              rpy="${gripper_base_link_orient_r} ${gripper_base_link_orient_p} ${gripper_base_link_orient_y}"/>
      <parent link="arm_5_link"/>
      <child link="gripper_base_link"/>
    </joint>

    <!-- ### finger_left ### -->
    <!-- finger_left link -->
    <link name="finger_left_link">
      <inertial>
        <mass value="${finger_left_link_mass}"/>
        <inertia ixx="0.00001" ixy="0.000" ixz="0.000" iyy="0.00001" iyz="0.00001" izz="0.00001"/>
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://youbot_description/meshes/gripper_left_finger.dae"/>
        </geometry>
      </visual>
    </link>
    <!-- finger_left joint -->
    <joint name="finger_left_joint" type="prismatic">
      <origin xyz="${finger_left_link_pose_x} ${finger_left_link_pose_y} ${finger_left_link_pose_z}"/>
      <parent link="gripper_base_link"/>
      <child link="finger_left_link"/>
      <axis xyz="${finger_left_axis}"/>
      <limit lower="${finger_left_limit_min}" upper="${finger_left_limit_max}"
             effort="${finger_joint_effort}" velocity="${finger_joint_velocity}"/>
    </joint>
    <transmission name="tran6">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="finger_left_joint"/>
      <actuator name="motor6">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <!-- ### finger_right ### -->
    <!-- finger_right link -->
    <link name="finger_right_link">
      <inertial>
        <mass value="${finger_right_link_mass}"/>
        <inertia ixx="0.00001" ixy="0.000" ixz="0.000" iyy="0.00001" iyz="0.00001" izz="0.00001"/>
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://youbot_description/meshes/gripper_right_finger.dae"/>
        </geometry>
      </visual>
    </link>
    <!-- finger_right joint -->
    <joint name="finger_right_joint" type="prismatic">
      <origin xyz="${finger_right_link_pose_x} ${finger_right_link_pose_y} ${finger_right_link_pose_z}"/>
      <parent link="gripper_base_link"/>
      <child link="finger_right_link"/>
      <axis xyz="${finger_right_axis}"/>
      <limit lower="${finger_right_limit_min}" upper="${finger_right_limit_max}" effort="${finger_joint_effort}" velocity="${finger_joint_velocity}"/>
    </joint>
    <transmission name="tran7">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="finger_right_joint"/>
      <actuator name="motor7">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>

  <xacro:base/>
  <xacro:wheels position="fl" x="1" y="-1"/>
  <xacro:wheels position="fr" x="1" y="1"/>
  <xacro:wheels position="bl" x="-1" y="-1"/>
  <xacro:wheels position="br" x="-1" y="1"/>
  <xacro:arm_base/>
  <xacro:arm/>
  <!-- xacro:gripper/ -->
</robot>
